### ISSUE TITLE
Cargo build failing: OpenCV

### ISSUE THREAD

**Issue by Apprisco** [alborrajo/sheetesia#1]
Multiple tries including brew, unable to detect OpenCV using pkg-config

**Comment by jiekun** [comment]
Same on Ubuntu19.04
package opencv4 is not found by pkg-config

**Comment by alborrajo** [comment]
OpenCV doesn't generate pkg-config since version 4 unless specified when compiling. Check this issue on the opencv repository for more information: [https://github.com/opencv/opencv/issues/13154#issuecomment-456652297](url)
I hope this helps.

**Comment by Apprisco** [comment]
Do you know how to compile opencv4 in mac? Thank you!

**Comment by Apprisco** [comment]
Update: compiled opencv4, have brew install pkgconfig, so everything should be good now? Is that how it works? Never worked with opencv outside of python, this is sad.

**Comment by Apprisco** [comment]
Followed the build till sudo make install in this guide:
https://www.pyimagesearch.com/2018/08/17/install-opencv-4-on-macos/

**Comment by Apprisco** [comment]
Error update:
sing OpenCV headers from: /Users/andrewwoo/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.3/headers/4.1/opencv2
=== Generating code in: /Users/andrewwoo/Downloads/sh/target/debug/build/opencv-81f7ce4706a61926/out
thread 'main' panicked at 'OpenCV version from pkg-config: 4.0.0 must be from 4.1 branch because of the feature: opencv-41', /Users/andrewwoo/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.3/build.rs:183:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Seems like opencv 4.1 is needed, it may be a good idea to have that as a dependency in the project.

**Comment by alborrajo** [comment]
OpenCV 4.1 is already a dependency on the cargo.toml file, i'll update the README to reflect that to avoid any confusion
