### ISSUE TITLE
Midi production is very weird.

### ISSUE THREAD

**Issue by Apprisco** [alborrajo/sheetesia#2]
The note detection is very accurate, to my testing. However, the MIDI generation fails to recognize chords and places notes very weirdly. This might be due to glisses in the music.

**Comment by Apprisco** [comment]
Tempo detection is also very weird, a song with tempo 480(according to the midi, 160 originally) is set as tempo 6.

**Comment by alborrajo** [comment]
This project was made as an experiment to learn computer vision on my free time and is in a very early stage. Due to a lack of free time i stopped working on it, and by making it open source i was hoping it could be useful for somebody else as a starting point, or to improve it in any way.

**Comment by Apprisco** [comment]
Hmmm. Understood, I will definitely try to improve accuracy :)

**Comment by Apprisco** [comment]
Am I allowed to create a fork of this project?

**Comment by alborrajo** [comment]
Yes, of course, everyone is allowed to fork the project! Sorry for the late answer
