### ISSUE TITLE
Getting stderr

### ISSUE THREAD

**Issue by minifisk** [alborrajo/sheetesia#5]
I'm pretty sure to have followed all the steps, but something seems to generate problems. Any idea whats wrong?

`  === Generating code in: /Users/USERNAME/work/sheetesia/target/debug/build/opencv-cea0f8923e111ae3/out
  thread 'main' panicked at 'package opencv4 is not found by pkg-config: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"opencv4\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package opencv4 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `opencv4.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'opencv4\' found\n" } }', /Users/USERNAME/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/build.rs:168:58`

**Comment by alborrajo** [comment]
Seems that you dont have the opencv4 package, have you compiled opencv with the OPENCV_GENERATE_PKGCONFIG flag?
https://github.com/opencv/opencv/issues/13154#issuecomment-456652297
