### ISSUE TITLE
Does not run with any common video format

### ISSUE THREAD

**Issue by suftware** [alborrajo/sheetesia#9]
Just managed to install this after lots of OpenCV configuration errors (If anyone has issues related to that I can provide my list of commands etc.) but after I get an executable, it just says `:(` no matter what video I pass into it. I've downloaded the video and it plays fine on my computer (QuickTime, macOS Monterey) and I've converted it to MP4, M4V, and AVI formats - none of them successfully run on Sheetesia. 

For context, I am running this on a brand new AWS EC2 Ubuntu 18.04 LTS (since it was not working on macOS due to SIP issues I couldn't resolve, and didn't work on Kali for... Kali reasons). I've verified that the videos all play (VLC on Mac) and am very confused as to why the AVI in particular is failing (since it's the one I have found the most support for online when researching the opencv video handling). Any advice would be appreciated, or a new binary that works (since the precompiled alpha binary fails when I run it 'cannot open shared object file' and fails again when I point to the shared object files that 'GLIBC-2.33 not found').

**Comment by suftware** [comment]
Alternatively, is this project portable to Python? I am not too familiar with the libraries you've used and would be curious to see if a Python alternative is possible. If there are certain Rust-specific features though then that's entirely logical why it's implemented initially in Rust (off-topic but thought I'd put the thought out).

**Comment by alborrajo** [comment]
I haven't worked on this project for ages but it should be working with those formats. Make sure the piano is visible on the first frame of the video, you can try with this for example: https://github.com/alborrajo/sheetesia/files/5291377/megalovania.mp4.zip

**Comment by suftware** [comment]
Hmm... the file you uploaded doesn't run either, gives the same error. I'm running the command by programmatically setting the LD library path (ie. the command is `LD_LIBRARY_PATH=/usr/local/lib cargo run --release megalovania.mp4`) but both file and every convertible file type (MP4, MOV, AVI, M4V) just prints `:(` which as far as I can tell is from an error in parsing the video (near the top of `main.rs`). Have there been updates to the libraries used (or am I using too new libraries) or something along those lines, potentially?
